# Generated by Django 2.2.12 on 2022-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='dest',
            field=models.CharField(default=0, max_length=30, verbose_name='Qual seu destino?'),
            preserve_default=False,
        ),
    ]
