# Generated by Django 2.2.12 on 2022-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0002_auto_20220327_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicao',
            name='descricao',
            field=models.CharField(default=0, max_length=30, verbose_name='Descreva a barreira:'),
            preserve_default=False,
        ),
    ]
