# Generated by Django 2.2.12 on 2022-04-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0003_posicao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicao',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descreva a barreira:'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dest',
            field=models.CharField(max_length=100, verbose_name='Qual seu destino?'),
        ),
    ]
