# Generated by Django 2.2.12 on 2022-04-11 23:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0004_auto_20220407_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao_atual',
            fields=[
                ('id_po', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_django.Usuarios')),
            ],
        ),
    ]
