# Generated by Django 2.2.12 on 2022-04-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0006_auto_20220411_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicao_atual',
            old_name='id_po',
            new_name='id',
        ),
    ]
