# Generated by Django 2.2.12 on 2022-04-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0007_auto_20220411_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posicao_atual',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='posicao_atual',
            table='Posicao_atual',
        ),
    ]
